[project]
name = "adversarial-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "adversarial-robustness-toolbox>=1.20.1",
    "autoattack",
    "matplotlib>=3.11.1",
    "numpy>=2.5.1",
    "pillow>=12.3.0",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "torch>=2.13.0",
    "torchvision>=0.28.0",
    "transformers>=5.14.1",
]

[tool.uv.sources]
autoattack = { git = "https://github.com/fra31/auto-attack.git" }
